global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'helvetia-api'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'

  - job_name: 'helvetia-worker'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: '/metrics'
